use std::{env, fs, path::PathBuf};

fn main() {
    let Some(destination) = env::args_os().nth(1).map(PathBuf::from) else {
        eprintln!("usage: export_palettes <destination.js>");
        std::process::exit(2);
    };
    let json = serde_json::to_string(&polar_h10_output::source_palette_catalog())
        .expect("source palette catalog must serialize");
    let source = format!(
        "// Generated by polar-h10-output/examples/export_palettes.rs. Do not edit by hand.\nwindow.PolarSourcePalettes = Object.freeze({json}.map((palette) => Object.freeze({{ ...palette, light: Object.freeze(palette.light), dark: Object.freeze(palette.dark) }})));\n"
    );
    fs::write(&destination, source)
        .unwrap_or_else(|error| panic!("could not write {}: {error}", destination.display()));
}
